### ISSUE TITLE
Fix Paella player's horizontal alignment

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#862] opened 2023-05-26 14:44 UTC
Didn't find any other issue as this is not about portrait videos but videos in 
https://tobira.opencast.org/events/2008 and
https://tobira.opencast.org/events/2008/esc
which have different problems:

- Player canvas seems to be defined by horizontal size of the text area - but the vertical extension is not proportional 9:16. Mind you, this would probably result in an absurdly large video embed, let's see.
- Player canvas has (two) grey backgrounds which hopefully will be white in Paella 7 "ethz".
- Control bars don't disappear if you move your pointer away from the video. They should:
![grafik](https://github.com/elan-ev/tobira/assets/1752342/7d185b39-b368-42fc-af36-273d095bf82e)

**Comment by LukasKalbertodt** [comment] 2023-06-05 08:38
> https://tobira.opencast.org/events/2008

What the heck is the camera operator doing there between 0:25 and 0:40? :D

> Player canvas seems to be defined by horizontal size of the text area - but the vertical extension is not proportional 9:16.
>
> Player canvas has (two) grey backgrounds which hopefully will be white in Paella 7 "ethz".

The player container (as set by Tobira) in these cases is always the same aspect ratio as the video. The fact that Paella has these two grey backgrounds is due to what we discussed in our last meeting with the Paella devs: currently the single video layout uses a fixed 16:9 canvas. This means: Tobira gives a fixed rectangle to Paella (with an aspect ratio the same as the video). In that, Paella now puts a 16:9 rectangle. And in that, it puts the actual video. You can see how this goes wrong. You can see it well in your second example: there the video is 4:3, so the outer container is 4:3 as well and the dark-grey rectangle is 16:9.

Anyway, this will be fixed by Paella changing the single video layout to a "dynamic one", which basically just means: getting rid of this forced 16:9 rectangle.

Let's wait for that and then revisit the question how wide the video container should be.

> Control bars don't disappear if you move your pointer away from the video. They should:

I can reproduce that. Once I click outside the player (on the white background), the control bars disappear shortly after. So it is about having an element inside Paella focused I think.

**Comment by oas777** [comment] 2023-06-05 09:18
- It seems something changed since I visited https://tobira.opencast.org/events/2008 and created the ticket, at least the video now uses the full canvas/container (compare screenshots):

![grafik](https://github.com/elan-ev/tobira/assets/1752342/dd222cb6-2af0-475f-be4f-52b15fb93f49)

So yes, let's wait for upcoming changes. Not only for a dynamic layout, but also white canvass (cf. https://tinyurl.com/2pucbyx3)

- Control bars disappearing should not require clicking the mouse outside the player but happen automatically if you move the mouse away from the container/canvas.
- There's no camera operator, that's a very early tracking system which helped identifying late students...

**Comment by LukasKalbertodt** [comment] 2023-10-04 14:54
I reread this discussion and I think everything is either fixed or tracked by more specific issues.

> Player canvas seems to be defined by horizontal size of the text area - but the vertical extension is not proportional 9:16. Mind you, this would probably result in an absurdly large video embed, let's see.

This is fixed for single stream videos for sure, as we are using a "dynamic layout" there. For dual stream videos I just created #956 

> Player canvas has (two) grey backgrounds which hopefully will be white in Paella 7 "ethz".

This is tracked by #954 

> Control bars don't disappear if you move your pointer away from the video. They should:

That is fixed.

So let's close?

**Comment by owi92** [comment] 2023-10-04 15:35
Yup, let's close this (if you're asking me)

**Comment by LukasKalbertodt** [comment] 2023-10-04 15:44
As usual, I am asking the void. But if any of you answers, I'm happy as well. Closing now. @oas777 if I overlooked something you raised here, please create a new issue.

**Closed by LukasKalbertodt** 2023-10-04 15:44 UTC
Labels: area:frontend, area:player

**Comment by LukasKalbertodt** [comment] 2023-10-05 08:27
> Two videos (or more?) running at the same time at https://tobira.opencast.org/events/2019, isn't there a (web) law against that?

Good point, I opened https://github.com/elan-ev/tobira/issues/957

> Is the grey background (instead of white/black) at https://tobira.opencast.org/speakers/lecture/v/JCQp-90G2LS tracked in [Rethink paella background and/or video scaling #954](https://github.com/elan-ev/tobira/issues/954)?

As I understood it, the linked issue is also very much about that background color, yes.
