### ISSUE TITLE
Missing Player Toolbox Background

### ISSUE THREAD

**Issue by geichelberger** [elan-ev/tobira#955] opened 2023-10-03 10:09 UTC
The player toolbox is missing the semi-transparent background from PR https://github.com/elan-ev/tobira/pull/938
![grafik](https://github.com/elan-ev/tobira/assets/35195803/124fe30b-27bc-48e0-b1e2-582b03f95f79)

**Comment by LukasKalbertodt** [comment] 2023-10-04 14:30
Where is that missing? On tobira.opencast.org? In what browser? I can't reproduce that right now. Have you tried a hard refresh? Are there any errors in the browser tools console?

**Comment by geichelberger** [comment] 2023-10-04 15:18
Strange, I tried it after your PR was merged, and it worked. Yesterday, it did not work, and today it's working again 🤷‍♂️. I am using Fedora 38 with Firefox. The screenshot is from tobira.opencast.org, and there was no error in the console.

**Comment by LukasKalbertodt** [comment] 2023-10-05 08:20
Hu ok, weird. So let's close this for now? If it happens again, just reopen. But let's hope its not happening again :grimacing:

**Closed by LukasKalbertodt** 2023-10-05 08:20 UTC
